# Generated by Django 5.0.6 on 2025-11-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_darkness',
            field=models.FloatField(default=0.55, help_text='0 = none, 0.85 = very dark overlay'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
