# Generated by Django 5.0.6 on 2025-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sitesettings_hero_bg_darkness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_kicker',
            field=models.CharField(blank=True, help_text="Small label above the title, e.g., 'DevOps • Cloud • Networking'", max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_side_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
