# Generated by Django 5.0.6 on 2025-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_sitesettings_hero_kicker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_logo',
            field=models.ImageField(blank=True, help_text='Separate logo for the navigation bar', null=True, upload_to='branding/'),
        ),
    ]
