# Generated by Django 5.0.6 on 2025-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_sitesettings_navbar_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('IDs', 'IDs'), ('Docs', 'Docs'), ('Photos', 'Photos'), ('Others', 'Others')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('text_content', models.TextField(blank=True, help_text='For IDs (number) or Others (notes)')),
                ('file', models.FileField(blank=True, help_text='For Docs', null=True, upload_to='personal_docs/')),
                ('image', models.ImageField(blank=True, help_text='For Photos', null=True, upload_to='personal_photos/')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
