# Generated by Django 5.0.6 on 2025-11-23 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_personalitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitem',
            name='image',
            field=models.ImageField(blank=True, help_text='For Photos or primary ID image', null=True, upload_to='personal_photos/'),
        ),
        migrations.CreateModel(
            name='PersonalItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='personal_photos/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.personalitem')),
            ],
        ),
    ]
